### ISSUE TITLE
Publisher level Auto-approval not working

### ISSUE THREAD

**Issue by miguelverweij** [microsoft/PowerPlatform-Catalog#16]
**Describe the bug**
The documentation states that when Allow Auto-approval is enabled, submissions for that publisher are approved automatically. This was not working for me.

**To Reproduce**
Tells us how you got to this behavior:
1. Global setting off
2. Publisher setting turned on
3. Submit through PAC CLI
4. See that the submission requires an approval

**Screenshots**
Publisher settings:
![image](https://github.com/microsoft/PowerPlatform-Catalog/assets/50626860/3d04d7d8-2492-4de5-9789-2ce22d6177f1)

Submission:
![image](https://github.com/microsoft/PowerPlatform-Catalog/assets/50626860/d9fdd5c1-804c-48bb-8cab-b429d5683212)

**App Info (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: 1.1.15.500

**Additional context**

**Comment by MattB-msft** [comment]
Currently, 
this is configured as a 2-stage lock and is only effective on the second publish / update.   
Both the Publisher and the Catalog item need to be set to enable auto approval.   

For it to work, the following conditions need to be in place: 
1) Publisher needs to have Auto Approve enabled. 
2) The Catalog Item needs to have Auto Approve enabled. 


The reasoning here is that an Auto Approval process would be applied only after the catalog item was initially validated, and 'trusted'.  Thus Trusting the Publisher and Trusting the Catalog Item they submitted. 
This also allow you to deny auto approval to all catalog items that a publisher has, or selectively block auto approval of a specific catalog item due to some issue or a need to block revisions to it. 


Let us know if this enables it for you

**Comment by miguelverweij** [comment]
That clarifies it for me. Thanks! Works as a charm now.

**Comment by MattB-msft** [comment]
Happy to help
